version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    reviewers: []
    labels:
      - dependencies
    commit-message:
      prefix: chore
      include: scope

