name: Code Review

on:
  pull_request:
    branches: [ "main" ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ESLint
        run: |
          if npm run lint; then
            echo "✅ Code style checks passed."
          else
            echo "❌ Linting issues found."
            exit 1
          fi

      - name: CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Security Check Result
        run: echo "✅ Security analysis completed successfully."
