name: Dependency Updates

on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot Metadata
        uses: dependabot/fetch-metadata@v2
        id: metadata
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Report
        run: echo "✅ Dependabot metadata fetched successfully."
