name: Dependency Updates

on:
  schedule:
    - cron: '0 19 * * *'  # daily at 00:00 PKT (UTC+5)
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  dependabot-auto-merge:
    if: ${{ github.event_name == 'pull_request' && github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Run tests
        run: |
          if npm run | grep -q "^  test"; then
            echo "Running tests..."
            npm test
          else
            echo "No 'test' script found. Skipping tests."
          fi

      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-approve and merge minor/patch
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-minor' || steps.metadata.outputs.update-type == 'version-update:semver-patch' }}
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr review "$PR_URL" --approve
          gh pr merge --auto --squash "$PR_URL"

  report-no-pr:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: No Dependabot PR found
        run: echo "Workflow ran on '${{ github.event_name }}'; no Dependabot PR to auto-merge."
