name: Dependency Updates

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  dependabot-auto-merge:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Run tests
        run: npm test || echo "No tests configured"

      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  report-no-pr:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: No Dependabot PR found
        run: echo "Workflow ran on '${{ github.event_name }}'; no Dependabot PR to auto-merge."
      - name: Auto-approve and merge minor/patch
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          UPDATE_TYPE: ${{ steps.metadata.outputs.update-type }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Update type: $UPDATE_TYPE"
          if [[ "$UPDATE_TYPE" == "version-update:semver-minor" || "$UPDATE_TYPE" == "version-update:semver-patch" ]]; then
            gh pr review "$PR_URL" --approve
            gh pr merge --auto --squash "$PR_URL"
          else
            echo "Non-minor update; skipping auto-merge."
          fi
