name: Release Notes Generator

on:
  push:
    tags:
      - 'v*.*.*'
  release:
    types: [created]
  workflow_dispatch:
  schedule:
    - cron: '*/2 * * * *'  # every 2 minutes

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Release Notes
        run: |
          echo "Release generated at $(date)" > release-notes.txt
          echo "✅ Release notes generated successfully."

      - name: Upload Notes
        uses: actions/upload-artifact@v4
        with:
          name: release-notes
          path: release-notes.txt
