name: Scheduled Data Updates

on:
  schedule:
    - cron: '0 6 * * *'  # daily at 6 AM UTC
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Show tool versions
        run: |
          node -v
          npm -v
          echo "Node.js version check passed"

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Run data scraping
        run: |
          echo "Starting data update at $(date)"
          echo "Current directory: $(pwd)"
          echo "Contents before scraping:"
          ls -la public/data/ || echo "No data directory found"
          
          # Run the scraping script with error handling
          if node run.js; then
            echo "✅ Data scraping completed successfully"
            echo "Contents after scraping:"
            ls -la public/data/ || echo "Still no data directory"
            ls -la public/data/satellite25544/ || echo "No satellite data directory"
          else
            echo "❌ Data scraping failed"
            echo "Creating backup log file"
            echo "Backup at $(date)" > public/data/backup-log.txt
            exit 1
          fi

      - name: Commit and push updated data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/data/
          git diff --staged --quiet || git commit -m "Update satellite data - $(date)"
          git push

      - name: Upload backup log
        uses: actions/upload-artifact@v4
        with:
          name: data-update-$(date +%Y%m%d)
          path: public/data/
          if-no-files-found: warn
