name: Scheduled Maintenance

on:
  schedule:
    - cron: '0 0 * * *'  # daily midnight UTC
  workflow_dispatch:

jobs:
  maintenance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Maintenance Script
        run: |
          echo "Starting maintenance..."
          echo "Backup at $(date)" > backup.txt
          echo "✅ Maintenance task completed successfully."

      - name: Upload Backup Log
        uses: actions/upload-artifact@v4
        with:
          name: daily-backup
          path: backup.txt
