name: Scheduled Data Updates

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '*/2 * * * *'  # every 2 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Show tool versions
        run: |
          node -v
          npm -v
          echo "Node.js version check passed"

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Run data scraping
        run: |
          echo "Starting data update at $(date)"
          node run.js
          echo "✅ Data update completed successfully"

      - name: Commit and push updated data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/data/
          git diff --staged --quiet || git commit -m "Update satellite data - $(date)"
          git push

      - name: Trigger Vercel deploy (optional)
        if: ${{ success() && env.VERCEL_DEPLOY_HOOK_URL != '' }}
        env:
          VERCEL_DEPLOY_HOOK_URL: ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
        run: |
          echo "Triggering Vercel deploy via hook..."
          curl -X POST -sS "$VERCEL_DEPLOY_HOOK_URL" || true

      - name: Upload backup log
        uses: actions/upload-artifact@v4
        with:
          name: data-update-$(date +%Y%m%d)
          path: public/data/
