name: Test Data Scraping

on:
  workflow_dispatch:

jobs:
  test-scraping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Show environment info
        run: |
          echo "Node.js version: $(node -v)"
          echo "NPM version: $(npm -v)"
          echo "Current directory: $(pwd)"
          echo "Contents:"
          ls -la

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Test data scraping
        run: |
          echo "Starting test scraping at $(date)"
          echo "Contents before scraping:"
          ls -la public/data/ || echo "No data directory found"
          
          # Run with timeout and error handling
          if timeout 60s node run.js; then
            echo "✅ Scraping completed successfully"
            echo "Contents after scraping:"
            ls -la public/data/ || echo "Still no data directory"
            if [ -d "public/data/satellite25544" ]; then
              echo "Satellite data directory contents:"
              ls -la public/data/satellite25544/ | head -10
              echo "Index.json size:"
              ls -lh public/data/satellite25544/index.json || echo "No index.json found"
            else
              echo "❌ No satellite data directory created"
            fi
          else
            echo "❌ Scraping failed or timed out"
            echo "Creating test log"
            echo "Test failed at $(date)" > public/data/test-log.txt
          fi

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-scraping-results
          path: public/data/
          if-no-files-found: warn
